apiVersion: v1
kind: Service
metadata:
  name: cloud-app-svc
  namespace: formation-k8s
  labels:
    app: cloud-app
spec:
  type: NodePort
  selector:
    app: cloud-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
